#!/bin/bash
#
# The 'run' performs a simple test that verifies that image
#
# IMAGE_NAME specifies a name of the candidate image used for testing.
# The image has to be available before this script is executed.
#

IMAGE_NAME=${IMAGE_NAME-ausnimbus/memcached:latest}
VERSION=${VERSION-"latest"}

VERSION_COMMAND="memcached -V"

extra_tests() {
  echo "Nothing yet"
}

test_dir="$(readlink -zf $(dirname "${BASH_SOURCE[0]}"))"
source ${test_dir}/../common/tests/component
