#!/bin/bash

NAME="memcached"
DISPLAY_NAME="Memcached"
TYPE="component"
VARIANTS="default,alpine"
VERSIONS="1.4"

DOCKER_PUSH=${DOCKER_PUSH:-"false"}

source $(readlink -zf $(dirname "${BASH_SOURCE[0]}"))/../common/hack/run
